"""departement table

Revision ID: 9324e5369d41
Revises: fff877520ca0
Create Date: 2023-12-06 13:16:52.964157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.database import Base
import fastapi_users_db_sqlalchemy



# revision identifiers, used by Alembic.
revision: str = '9324e5369d41'
down_revision: Union[str, None] = 'fff877520ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('department_head_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_head_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
