"""init

Revision ID: a9fb4d8e5e5a
Revises: 
Create Date: 2023-12-06 12:40:05.912557

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from backend.database import Base

# revision identifiers, used by Alembic.
revision: str = "a9fb4d8e5e5a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
